---
version: '3.7'
services:
  meteor:
    build:
      context: ../../
      dockerfile: docker/compose/mozdef_meteor/Dockerfile
      args:
        METEOR_BUILD: 'NO'
    restart: always
    command: bash -c 'node -i'
    depends_on:
      - mongodb
      - rest
    networks:
      - default
    volumes:
        - ../../meteor:/opt/mozdef/envs/mozdef/meteor
    stdin_open: true
    tty: true
